config/routes.rb
Eightbitbacklog::Application.routes.draw do

  get 'home/index'
  get 'search', to: 'pages#search'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "pages/index"

  root 'pages#index'
  
  resource :games
  
  get 'gamelist', to: 'users#gamelist'
  delete 'gamelist', to: 'gamelists#destroy'
  
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  has_many :gameconcepts
  has_many :games, through: :gameconcepts
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :gamedevelopers, dependent: :destroy
  has_many :games, through: :gamedevelopers
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :gamelistgames, dependent: :destroy
  has_many :gameconcepts, dependent: :destroy
  has_many :gamegenres, dependent: :destroy
  has_many :gameplatforms, dependent: :destroy
  has_many :gamedevelopers, dependent: :destroy
  has_many :gamepublishers, dependent: :destroy
  has_many :gamelists,  through: :gamelistgames
  has_many :concepts,   through: :gameconcepts
  has_many :genres,     through: :gamegenres
  has_many :platforms,  through: :gameplatforms
  has_many :developers, through: :gamedevelopers
  has_many :publishers, through: :gamepublishers
end

app/models/gameconcept.rb
class Gameconcept < ActiveRecord::Base
  belongs_to :game
  belongs_to :concept
end

app/models/gamedeveloper.rb
class Gamedeveloper < ActiveRecord::Base
  belongs_to :game
  belongs_to :developer
end

app/models/gamegenre.rb
class Gamegenre < ActiveRecord::Base
  belongs_to :game
  belongs_to :genre
end

app/models/gamelist.rb
class Gamelist < ActiveRecord::Base
  belongs_to :user
  has_many   :gamelistgames, dependent: :destroy
  has_many   :games, through: :gamelistgames
    
  def popular_genres
    @games = self.games
    @genres = Hash.new
    @games.each do |game|
      game.genres.each do |genre|
        if @genres[genre.name].nil?
          @genres[genre.name] = 1
        else
          @genres[genre.name] += 1
        end
      end
    end
    @genres = Hash[@genres.sort_by {|_, v| v}.reverse]
    @genres.first(5)
  end
  
  def popular_platforms
    @games = self.games
    @platforms = Hash.new
    @games.each do |game|
      game.platforms.each do |platform|
        if @platforms[platform.name].nil?
          @platforms[platform.name] = 1
        else
          @platforms[platform.name] += 1
        end
      end
    end
    @platforms = Hash[@platforms.sort_by {|_, v| v}.reverse]    
    @platforms.first(5)
  end
  
  def popular_developers
    @games = self.games
    @developers = Hash.new
    @developers.each do |game|
      game.developers.each do |developer|
        if @developers[genre.name].nil?
          @developers[genre.name] = 1
        else
          @developers[genre.name] += 1
        end
      end
    end
    @developers = Hash[@developers.sort_by {|_, v| v}.reverse]
    @developers.first(5)
  end
end

app/models/gamelistgame.rb
class Gamelistgame < ActiveRecord::Base
  belongs_to :gamelist
  belongs_to :game
  has_many   :gamelistgameplatforms
  has_many   :platforms, through: :gamelistgameplatforms
end

app/models/gamelistgameplatform.rb
class Gamelistgameplatform < ActiveRecord::Base
  belongs_to :gamelistgame
  belongs_to :platform
end

app/models/gameplatform.rb
class Gameplatform < ActiveRecord::Base
  belongs_to :game
  belongs_to :platform
end

app/models/gamepublisher.rb
class Gamepublisher < ActiveRecord::Base
  belongs_to :game
  belongs_to :publisher
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :gamegenres, dependent: :destroy
  has_many :games, through: :gamegenres
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :gameplatforms, dependent: :destroy
  has_many :games, through: :gameplatforms
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :gamepublishers, dependent: :destroy
  has_many :games, through: :gamepublishers
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :gamelist, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook, :twitter]
  after_save :create_game_list

  attr_accessor :login
  
#   validates_uniqueness_of :username
#   validates_presence_of :username
#   validates_presence_of :email
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:username)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end
  
  def self.find_for_facebook_oauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else

        user = User.create(username:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end
  
  
  def create_game_list
  	gamelist = self.build_gamelist()
  	gamelist.save
  end

	def has_game?(game)
		self.gamelist.games.include?(game)
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def create
		@game = Game.where(giantbomb_id: params[:game][:game_id]).first
		current_user.gamelist.gamelistgames.create(game_id: @game.id)
		if params[:game][:platforms]
		  params[:game][:platforms][:id].each do |platform|
		    current_user.gamelist.gamelistgames.where(game_id: @game.id).first.gamelistgameplatforms.create(platform_id: platform)
		  end
		end

		respond_to do |format|
			format.js {}
			format.html {redirect_to search_path(query: params[:game][:query], page: params[:game][:page])}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>8-bit Backlog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapsed">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">8-Bit Bucketlist</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapsed">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?(pages_index_path) %>"><%= link_to "Home", pages_index_path %></li>
        <li class="<%= "active" if current_page?(gamelist_path)%>"><%= link_to "My Games", gamelist_path %></li>
      </ul>
        <form class="navbar-form navbar-left" role="search">
          <% form_tag search_path, method: :get do %>
          <div class="form-group">
            <%= text_field_tag :query, params[:query], :class => "form-control" %>
          </div>
            <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
          <% end %>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-lg"></i>&nbsp;<%= current_user.username %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
              <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
        </ul>
    </div>
  </div>
</nav>

<div class="alert alert-info"><p class="notice"><%= notice %></p></div>
<div class="alert alert-warning"><p class="alert"><%= alert %></p></div>
<p class="notice" id="notice" style="display: none;"></p>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Hi there!</h1>
    <p>Welcome to 8-Bit Bucketlist! <br>
    8BBL allows you to search for games and add them to your collection. From there, you can keep track of what games you have beaten and even get recommendations on new games to play!</p>
  </div>
</div>

app/views/pages/search.html.erb
<div id="search_result">
	<% if !@results.empty? %>
		<% @results.each do |result|  %>
			<div class="well game">
				<div class="name">
					<%= result.name %>
				</div>
				<div class="description">
					<%= result.deck %>
				</div>
				<% if !result.developers.nil? %>
					<div class="developers">
						<% result.developers.each do |developer| %>
							<span class="badge" style="background-color:#428BCA;"><%= developer["name"] %></span>
						<% end %>
					</div>
				<% end %>
				<% if !result.genres.nil? %>
					<div class="genres">
						<% result.genres.each do |genre| %>
						<span class="badge" style="background-color: #c0392b;"><%= genre["name"] %></span>
						<% end %>
					</div>
				<% end %>
				<% if user_signed_in? %>
					<% if current_user.has_game?(result) %>
						<div><%= fa_icon "check" %> Game is already in List</div>
					<% else %>
						<%= form_for Game.new do |f| %>
							<%= f.hidden_field :game_id, value: result.giantbomb_id %>
							<%= f.hidden_field :page, value: @page %>
							<%= f.hidden_field :query, value: @query %>
		          <% result.platforms.each do |platform| %>
		            <span class='select_platform'>
									<label class="badge platform">
										<%= check_box_tag "game[platforms][id][]", platform.id, false %>
										<%= platform.name %>
									</label>
		            </span>
		          <% end %>
							<button class = "btn-primary btn"><%= fa_icon "plus" %>&nbsp;Add Game to List</button>
						<% end %>
					<% end %>
				<% else %>
					<% if !result.platforms.nil? %>
						<div class="platforms">
							<% result.platforms.each do |platform| %>
								<span class="badge"><%= platform.abbreviation %></span>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>
		<ul class="pager">
		  <% if @previous != 0 %>
		    <li><%= link_to "Previous", search_path(query: @query, page: @previous) %></li>
		  <% else %>
		    <li readonly = "readonly" ><a href="javascript:void(0)">Previous</a></li>
		  <% end %>
		  <% if @next != 0 %>
		    <li><%= link_to "Next", search_path(query: @query, page: @next) %></li>
		  <% else %>
		    <li readonly = "readonly"><a href="javascript:void(0)">Next</a></li>
		  <% end %>
		</ul>
	<% else %>
		We were unable to find a game by the name of <%= @query %>
	<% end %>
</div>
<script>
	$(".platform").on("click", function( e ){
		if( e.target.tagName.toUpperCase() !== 'INPUT' ) {
			$(this).toggleClass("checked");
        var cbox = $(this).find('input:checkbox')[0];
        cbox.checked = !cbox.checked;
    }
	});
</script>